"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-05 14:23:26.511595
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fake_provider_calls',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer_md', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_entries_locale'), 'faq_entries', ['locale'], unique=False)
    op.create_table('message_templates',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_template_ref', sa.String(length=120), nullable=False),
    sa.Column('variables', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key', 'locale', 'provider')
    )
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_phone_e164'), 'otp_codes', ['phone_e164'], unique=False)
    op.create_table('site_config',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('staff_users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('admin', 'catalog_editor', 'ops_coordinator', 'support_agent', 'finance', name='staff_role'), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_confirmed', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('temples',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('lat', sa.Double(), nullable=True),
    sa.Column('lng', sa.Double(), nullable=True),
    sa.Column('presiding_deity', sa.String(length=120), nullable=False),
    sa.Column('venue_type', sa.Enum('temple', 'yagashala', 'ghat', 'kund', name='venue_type'), nullable=False),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('whatsapp_opt_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marketing_opt_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletion_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_e164')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_staff_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('diff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_staff_id'], ['staff_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_at'), 'audit_log', ['at'], unique=False)
    op.create_table('family_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('relation', sa.String(length=60), nullable=True),
    sa.Column('gotra', sa.String(length=80), nullable=True),
    sa.Column('nakshatra', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_members_user_id'), 'family_members', ['user_id'], unique=False)
    op.create_table('pujas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('temple_id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.Enum('one_time', 'seva', 'chadhava', name='puja_kind'), nullable=False),
    sa.Column('deity_tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('dosha_tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('benefit_tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('tradition', sa.String(length=120), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('priests_count', sa.Integer(), nullable=False),
    sa.Column('sankalp_language', sa.String(length=40), nullable=False),
    sa.Column('requires_nakshatra', sa.Boolean(), nullable=False),
    sa.Column('video_sla_hours', sa.Integer(), nullable=True),
    sa.Column('deliverables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prasad_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='publish_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pujas_temple_id'), 'pujas', ['temple_id'], unique=False)
    op.create_table('temple_translations',
    sa.Column('temple_id', sa.BigInteger(), nullable=False),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('history_md', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('temple_id', 'locale')
    )
    op.create_table('addon_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('puja_id', sa.BigInteger(), nullable=True),
    sa.Column('image_key', sa.String(length=300), nullable=True),
    sa.Column('price_inr_minor', sa.Integer(), nullable=False),
    sa.Column('price_usd_minor', sa.Integer(), nullable=False),
    sa.Column('max_qty', sa.Integer(), nullable=False),
    sa.Column('ships_home', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['puja_id'], ['pujas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addon_items_puja_id'), 'addon_items', ['puja_id'], unique=False)
    op.create_table('callback_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('puja_id', sa.BigInteger(), nullable=True),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['puja_id'], ['pujas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('template_key', sa.String(length=60), nullable=False),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('interest_tag', sa.String(length=60), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('puja_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('recipients', sa.Integer(), nullable=False),
    sa.Column('skipped_cap', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['puja_id'], ['pujas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('puja_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.Enum('individual', 'couple', 'family', name='package_code'), nullable=False),
    sa.Column('max_names', sa.Integer(), nullable=False),
    sa.Column('price_inr_minor', sa.Integer(), nullable=False),
    sa.Column('price_usd_minor', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['puja_id'], ['pujas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_puja_id'), 'packages', ['puja_id'], unique=False)
    op.create_table('puja_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('puja_id', sa.BigInteger(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('booking_cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('video_sla_hours', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'started', 'performed', 'disrupted', 'cancelled', name='event_status'), nullable=False),
    sa.Column('sankalp_sheet_key', sa.String(length=300), nullable=True),
    sa.Column('sankalp_video_stream_id', sa.String(length=300), nullable=True),
    sa.Column('full_video_stream_id', sa.String(length=300), nullable=True),
    sa.Column('sankalp_video_key', sa.String(length=300), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disrupted_action', sa.String(length=20), nullable=True),
    sa.Column('rescheduled_to_event_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['puja_id'], ['pujas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rescheduled_to_event_id'], ['puja_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_puja_events_booking_cutoff_at'), 'puja_events', ['booking_cutoff_at'], unique=False)
    op.create_index(op.f('ix_puja_events_puja_id'), 'puja_events', ['puja_id'], unique=False)
    op.create_index(op.f('ix_puja_events_starts_at'), 'puja_events', ['starts_at'], unique=False)
    op.create_table('puja_translations',
    sa.Column('puja_id', sa.BigInteger(), nullable=False),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=300), nullable=True),
    sa.Column('occasion_chip', sa.String(length=80), nullable=True),
    sa.Column('about_md', sa.Text(), nullable=True),
    sa.Column('benefits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rituals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('faqs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.String(length=320), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['puja_id'], ['pujas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('puja_id', 'locale')
    )
    op.create_table('seva_plans',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('puja_id', sa.BigInteger(), nullable=False),
    sa.Column('rrule', sa.Text(), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('autopay_allowed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['puja_id'], ['pujas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('puja_id')
    )
    op.create_table('wishlist_items',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('puja_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['puja_id'], ['pujas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'puja_id')
    )
    op.create_table('addon_item_translations',
    sa.Column('addon_item_id', sa.BigInteger(), nullable=False),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['addon_item_id'], ['addon_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('addon_item_id', 'locale')
    )
    op.create_table('media_assets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('temple_id', sa.BigInteger(), nullable=True),
    sa.Column('puja_event_id', sa.BigInteger(), nullable=True),
    sa.Column('taken_on', sa.Date(), nullable=True),
    sa.Column('alt', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('in_gallery', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['puja_event_id'], ['puja_events.id'], ),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('seva_plan_id', sa.BigInteger(), nullable=False),
    sa.Column('package_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_mode', sa.Enum('full', 'autopay', name='payment_mode'), nullable=False),
    sa.Column('mandate_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('active', 'cancelled', 'completed', 'mandate_failed', name='subscription_status'), nullable=False),
    sa.Column('next_occurrence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mandate_id'], ['mandates.id'], name='fk_subscriptions_mandate', use_alter=True),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['seva_plan_id'], ['seva_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('puja_event_id', sa.BigInteger(), nullable=False),
    sa.Column('package_id', sa.BigInteger(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal_minor', sa.Integer(), nullable=False),
    sa.Column('addons_minor', sa.Integer(), nullable=False),
    sa.Column('shipping_minor', sa.Integer(), nullable=False),
    sa.Column('dakshina_minor', sa.Integer(), nullable=False),
    sa.Column('tax_minor', sa.Integer(), nullable=False),
    sa.Column('total_minor', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_payment', 'confirmed', 'locked', 'performed', 'proof_ready', 'proof_sent', 'completed', 'cancelled', 'refunded', 'rescheduled', name='booking_status'), nullable=False),
    sa.Column('whatsapp_e164', sa.String(length=20), nullable=True),
    sa.Column('wish', sa.String(length=140), nullable=True),
    sa.Column('consent_whatsapp_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_text_version', sa.String(length=20), nullable=True),
    sa.Column('consent_marketing_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proof_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.String(length=60), nullable=True),
    sa.Column('payment_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proof_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_breach_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reschedule_from_event_id', sa.BigInteger(), nullable=True),
    sa.Column('reschedule_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('needs_call_reason', sa.String(length=120), nullable=True),
    sa.Column('assisted_by_staff_id', sa.BigInteger(), nullable=True),
    sa.Column('sheet_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assisted_by_staff_id'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['puja_event_id'], ['puja_events.id'], ),
    sa.ForeignKeyConstraint(['reschedule_from_event_id'], ['puja_events.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('proof_token')
    )
    op.create_index(op.f('ix_bookings_puja_event_id'), 'bookings', ['puja_event_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_subscription_id'), 'bookings', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('mandates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=120), nullable=True),
    sa.Column('max_amount_minor', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mandates_subscription_id'), 'mandates', ['subscription_id'], unique=False)
    op.create_table('booking_addons',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('addon_item_id', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price_minor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['addon_item_id'], ['addon_items.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_id', 'addon_item_id')
    )
    op.create_table('booking_names',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('relation', sa.String(length=60), nullable=True),
    sa.Column('gotra', sa.String(length=80), nullable=True),
    sa.Column('gotra_unknown', sa.Boolean(), nullable=False),
    sa.Column('nakshatra', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_names_booking_id'), 'booking_names', ['booking_id'], unique=False)
    op.create_table('booking_notes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_notes_booking_id'), 'booking_notes', ['booking_id'], unique=False)
    op.create_table('inbound_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_e164', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('button_payload', sa.String(length=200), nullable=True),
    sa.Column('matched_booking_id', sa.UUID(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matched_booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbound_messages_from_e164'), 'inbound_messages', ['from_e164'], unique=False)
    op.create_table('message_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('template_key', sa.String(length=60), nullable=False),
    sa.Column('occurrence_key', sa.String(length=80), nullable=False),
    sa.Column('to_e164', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_message_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('queued', 'sent', 'delivered', 'read', 'failed', name='message_status'), nullable=False),
    sa.Column('error_code', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('button_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('header_media_url', sa.String(length=500), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('campaign_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'template_key', 'occurrence_key', name='uq_message_log_booking_tpl_occ')
    )
    op.create_index('ix_message_log_due', 'message_log', ['status', 'scheduled_for'], unique=False)
    op.create_index(op.f('ix_message_log_provider_message_id'), 'message_log', ['provider_message_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_order_id', sa.String(length=100), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=100), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_order_id'), 'payments', ['provider_order_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_payment_id'), 'payments', ['provider_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_table('proof_clips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('puja_event_id', sa.BigInteger(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.Column('stream_id', sa.String(length=300), nullable=True),
    sa.Column('r2_key', sa.String(length=300), nullable=True),
    sa.Column('thumb_key', sa.String(length=300), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('qc_status', sa.Enum('pending', 'approved', 'rejected', name='qc_status'), nullable=False),
    sa.Column('sent_inline', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['puja_event_id'], ['puja_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index(op.f('ix_proof_clips_puja_event_id'), 'proof_clips', ['puja_event_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('locale', sa.String(length=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='review_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('provider_order_id', sa.String(length=100), nullable=True),
    sa.Column('awb', sa.String(length=60), nullable=True),
    sa.Column('courier', sa.String(length=80), nullable=True),
    sa.Column('tracking_url', sa.String(length=300), nullable=True),
    sa.Column('label_url', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('pending', 'packed', 'shipped', 'out_for_delivery', 'delivered', 'returned', name='shipment_status'), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index(op.f('ix_shipments_awb'), 'shipments', ['awb'], unique=False)
    op.create_table('reconciliation_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=100), nullable=True),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_items_run_date'), 'reconciliation_items', ['run_date'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('provider_refund_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_booking_id'), 'refunds', ['booking_id'], unique=False)
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=False)
    op.create_index(op.f('ix_refunds_provider_refund_id'), 'refunds', ['provider_refund_id'], unique=False)
    # ### end Alembic commands ###
    op.create_foreign_key('fk_subscriptions_mandate', 'subscriptions', 'mandates', ['mandate_id'], ['id'])
    op.execute("CREATE INDEX ix_puja_tr_title_trgm ON puja_translations USING gin (title gin_trgm_ops)")
    op.execute("CREATE INDEX ix_temple_tr_name_trgm ON temple_translations USING gin (name gin_trgm_ops)")


def downgrade() -> None:
    op.drop_constraint('fk_subscriptions_mandate', 'subscriptions', type_='foreignkey')
    op.execute("DROP INDEX IF EXISTS ix_puja_tr_title_trgm")
    op.execute("DROP INDEX IF EXISTS ix_temple_tr_name_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_provider_refund_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_booking_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_reconciliation_items_run_date'), table_name='reconciliation_items')
    op.drop_table('reconciliation_items')
    op.drop_index(op.f('ix_shipments_awb'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_proof_clips_puja_event_id'), table_name='proof_clips')
    op.drop_table('proof_clips')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_message_log_provider_message_id'), table_name='message_log')
    op.drop_index('ix_message_log_due', table_name='message_log')
    op.drop_table('message_log')
    op.drop_index(op.f('ix_inbound_messages_from_e164'), table_name='inbound_messages')
    op.drop_table('inbound_messages')
    op.drop_index(op.f('ix_booking_notes_booking_id'), table_name='booking_notes')
    op.drop_table('booking_notes')
    op.drop_index(op.f('ix_booking_names_booking_id'), table_name='booking_names')
    op.drop_table('booking_names')
    op.drop_table('booking_addons')
    op.drop_index(op.f('ix_mandates_subscription_id'), table_name='mandates')
    op.drop_table('mandates')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_subscription_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_puja_event_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('media_assets')
    op.drop_table('addon_item_translations')
    op.drop_table('wishlist_items')
    op.drop_table('seva_plans')
    op.drop_table('puja_translations')
    op.drop_index(op.f('ix_puja_events_starts_at'), table_name='puja_events')
    op.drop_index(op.f('ix_puja_events_puja_id'), table_name='puja_events')
    op.drop_index(op.f('ix_puja_events_booking_cutoff_at'), table_name='puja_events')
    op.drop_table('puja_events')
    op.drop_index(op.f('ix_packages_puja_id'), table_name='packages')
    op.drop_table('packages')
    op.drop_table('campaigns')
    op.drop_table('callback_requests')
    op.drop_index(op.f('ix_addon_items_puja_id'), table_name='addon_items')
    op.drop_table('addon_items')
    op.drop_table('temple_translations')
    op.drop_index(op.f('ix_pujas_temple_id'), table_name='pujas')
    op.drop_table('pujas')
    op.drop_index(op.f('ix_family_members_user_id'), table_name='family_members')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_audit_log_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('webhook_events')
    op.drop_table('users')
    op.drop_table('temples')
    op.drop_table('staff_users')
    op.drop_table('site_config')
    op.drop_index(op.f('ix_otp_codes_phone_e164'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_table('message_templates')
    op.drop_index(op.f('ix_faq_entries_locale'), table_name='faq_entries')
    op.drop_table('faq_entries')
    op.drop_table('fake_provider_calls')
    # ### end Alembic commands ###
    for t in ("staff_role","venue_type","puja_kind","publish_status","package_code","event_status","booking_status",
              "payment_mode","subscription_status","qc_status","shipment_status","message_status","review_status"):
        op.execute(f"DROP TYPE IF EXISTS {t}")
