"""Demo catalog for local dev and staging. Temples here are illustrative, not partner commitments.

Copy follows PRD §12: traditional purpose of each ritual, never a promised outcome.
"""

IMG = "/images/seed/{}.svg"


def alt(en, hi, ta, te):
    return {"en": en, "hi": hi, "ta": ta, "te": te}


TEMPLES = [
    {
        "slug": "sri-mallikarjuna-swamy-temple-vijayawada", "city": "Vijayawada", "state": "Andhra Pradesh",
        "lat": 16.5150, "lng": 80.6050, "presiding_deity": "Shiva (Mallikarjuna)", "venue_type": "temple",
        "photos": [{"key": IMG.format("temple-mallikarjuna"), "taken_on": "2026-08-14",
                    "alt": alt("Illustration of a temple gopuram in gold line art",
                               "सुनहरी रेखाओं में मंदिर गोपुरम का चित्र",
                               "தங்கக் கோடுகளில் கோவில் கோபுரத்தின் ஓவியம்",
                               "బంగారు గీతల్లో ఆలయ గోపుర చిత్రం")}],
        "tr": {
            "en": ("Sri Mallikarjuna Swamy Temple", "Indrakeeladri Road, Vijayawada, Andhra Pradesh",
                   "A Shiva temple on the banks of the Krishna where abhishekam is offered every morning by a family of hereditary archakas."),
            "hi": ("श्री मल्लिकार्जुन स्वामी मंदिर", "इंद्रकीलाद्रि रोड, विजयवाड़ा, आंध्र प्रदेश",
                   "कृष्णा नदी के तट पर स्थित शिव मंदिर, जहाँ वंशानुगत अर्चकों का परिवार हर सुबह अभिषेक करता है।"),
            "ta": ("ஸ்ரீ மல்லிகார்ஜுன ஸ்வாமி கோவில்", "இந்திரகீலாத்ரி சாலை, விஜயவாடா, ஆந்திரப் பிரதேசம்",
                   "கிருஷ்ணா நதிக்கரையில் உள்ள சிவன் கோவில்; பரம்பரை அர்ச்சகர் குடும்பம் தினமும் காலையில் அபிஷேகம் செய்கிறது."),
            "te": ("శ్రీ మల్లికార్జున స్వామి ఆలయం", "ఇంద్రకీలాద్రి రోడ్, విజయవాడ, ఆంధ్రప్రదేశ్",
                   "కృష్ణా నది ఒడ్డున ఉన్న శివాలయం; వంశపారంపర్య అర్చకుల కుటుంబం ప్రతి ఉదయం అభిషేకం చేస్తుంది."),
        },
    },
    {
        "slug": "navagraha-yagashala-kanchipuram", "city": "Kanchipuram", "state": "Tamil Nadu",
        "lat": 12.8342, "lng": 79.7036, "presiding_deity": "Navagraha", "venue_type": "yagashala",
        "photos": [{"key": IMG.format("temple-yagashala"), "taken_on": "2026-07-02",
                    "alt": alt("Illustration of a lamp inside a yagashala",
                               "यज्ञशाला में दीपक का चित्र", "யாகசாலையில் விளக்கின் ஓவியம்",
                               "యాగశాలలో దీపం చిత్రం")}],
        "tr": {
            "en": ("Navagraha Yagashala", "Near Ekambareswarar Temple, Kanchipuram, Tamil Nadu",
                   "A private yagashala run by a vedic pathashala, used for homams that need a fire altar and a full team of ritviks."),
            "hi": ("नवग्रह यज्ञशाला", "एकाम्बरेश्वर मंदिर के पास, कांचीपुरम, तमिलनाडु",
                   "एक वैदिक पाठशाला द्वारा संचालित निजी यज्ञशाला, जहाँ अग्निकुंड और ऋत्विकों की पूरी टीम वाले होम होते हैं।"),
            "ta": ("நவக்கிரக யாகசாலை", "ஏகாம்பரேஸ்வரர் கோவில் அருகில், காஞ்சிபுரம், தமிழ்நாடு",
                   "வேத பாடசாலை நடத்தும் தனியார் யாகசாலை; ஹோம குண்டமும் முழு ரித்விக் குழுவும் தேவைப்படும் ஹோமங்கள் இங்கு நடக்கின்றன."),
            "te": ("నవగ్రహ యాగశాల", "ఏకాంబరేశ్వర ఆలయం దగ్గర, కాంచీపురం, తమిళనాడు",
                   "వేద పాఠశాల నిర్వహించే ప్రైవేట్ యాగశాల; హోమ కుండం మరియు పూర్తి ఋత్విక్ బృందం అవసరమైన హోమాలు ఇక్కడ జరుగుతాయి."),
        },
    },
    {
        "slug": "dashashwamedh-ghat-varanasi", "city": "Varanasi", "state": "Uttar Pradesh",
        "lat": 25.3069, "lng": 83.0104, "presiding_deity": "Ganga", "venue_type": "ghat",
        "photos": [{"key": IMG.format("temple-ghat"), "taken_on": "2026-09-21",
                    "alt": alt("Illustration of river waves with a lamp", "नदी की लहरों और दीपक का चित्र",
                               "நதி அலைகளும் விளக்கும் கொண்ட ஓவியம்", "నది అలలు మరియు దీపం చిత్రం")}],
        "tr": {
            "en": ("Dashashwamedh Ghat", "Dashashwamedh Ghat Road, Varanasi, Uttar Pradesh",
                   "One of the oldest ghats on the Ganga. Tarpan and Ganga rituals are performed on the steps by the ghat's purohits."),
            "hi": ("दशाश्वमेध घाट", "दशाश्वमेध घाट रोड, वाराणसी, उत्तर प्रदेश",
                   "गंगा के सबसे प्राचीन घाटों में से एक। घाट के पुरोहित सीढ़ियों पर तर्पण और गंगा पूजन करते हैं।"),
            "ta": ("தசாஸ்வமேத் கட்", "தசாஸ்வமேத் கட் சாலை, வாராணசி, உத்தரப் பிரதேசம்",
                   "கங்கையின் மிகப் பழமையான படித்துறைகளில் ஒன்று. இங்குள்ள புரோகிதர்கள் படிகளில் தர்ப்பணமும் கங்கை பூஜையும் செய்கிறார்கள்."),
            "te": ("దశాశ్వమేధ ఘాట్", "దశాశ్వమేధ ఘాట్ రోడ్, వారణాసి, ఉత్తరప్రదేశ్",
                   "గంగానది అత్యంత ప్రాచీన ఘాట్‌లలో ఒకటి. ఘాట్ పురోహితులు మెట్లపై తర్పణం మరియు గంగా పూజ చేస్తారు."),
        },
    },
    {
        "slug": "sri-mahalakshmi-temple-hyderabad", "city": "Hyderabad", "state": "Telangana",
        "lat": 17.3850, "lng": 78.4867, "presiding_deity": "Mahalakshmi", "venue_type": "temple",
        "photos": [{"key": IMG.format("temple-lakshmi"), "taken_on": "2026-06-10",
                    "alt": alt("Illustration of a temple shrine", "मंदिर गर्भगृह का चित्र",
                               "கோவில் சன்னதியின் ஓவியம்", "ఆలయ గర్భగుడి చిత్రం")}],
        "tr": {
            "en": ("Sri Mahalakshmi Temple", "Old City, Hyderabad, Telangana",
                   "A neighbourhood Lakshmi temple known for its Friday kumkumarchana and its long-serving priests."),
            "hi": ("श्री महालक्ष्मी मंदिर", "पुराना शहर, हैदराबाद, तेलंगाना",
                   "मोहल्ले का लक्ष्मी मंदिर, जो शुक्रवार की कुमकुमार्चना और लंबे समय से सेवा कर रहे पुजारियों के लिए जाना जाता है।"),
            "ta": ("ஸ்ரீ மகாலட்சுமி கோவில்", "பழைய நகரம், ஹைதராபாத், தெலங்கானா",
                   "வெள்ளிக்கிழமை குங்குமார்ச்சனைக்கும் நீண்டகாலமாகப் பணியாற்றும் அர்ச்சகர்களுக்கும் பெயர் பெற்ற லட்சுமி கோவில்."),
            "te": ("శ్రీ మహాలక్ష్మి ఆలయం", "పాతబస్తీ, హైదరాబాద్, తెలంగాణ",
                   "శుక్రవారం కుంకుమార్చన మరియు దీర్ఘకాలంగా సేవ చేస్తున్న అర్చకులకు పేరుగాంచిన లక్ష్మీ ఆలయం."),
        },
    },
]


def T(title, subtitle, chip, about, benefits, rituals, faqs, meta_title, meta_desc):
    return {"title": title, "subtitle": subtitle, "occasion_chip": chip, "about_md": about,
            "benefits": [{"title": b[0], "line": b[1]} for b in benefits],
            "rituals": [{"title": r[0], "text": r[1], "main": bool(r[2]) if len(r) > 2 else False} for r in rituals],
            "faqs": [{"q": f[0], "a": f[1]} for f in faqs], "meta_title": meta_title, "meta_description": meta_desc}


PUJAS = [
    {
        "key": "rudrabhishekam", "temple": 0, "kind": "one_time", "slug": "rudrabhishekam",
        "deity_tags": ["shiva"], "dosha_tags": [], "benefit_tags": ["peace", "health"],
        "tradition": "Shaiva Agama", "duration_minutes": 90, "priests_count": 3, "sankalp_language": "Sanskrit",
        "requires_nakshatra": False, "deliverables": ["sankalp_clip", "full_video", "photos"],
        "prasad_box": ["vibhuti", "kumkum", "raksha_sutra"],
        "images": ["rudrabhishekam", "rudrabhishekam-2"],
        "image_alt": alt("Trident and bell illustration in gold", "सुनहरे त्रिशूल और घंटी का चित्र",
                         "தங்க நிறத் திரிசூலம் மற்றும் மணியின் ஓவியம்", "బంగారు త్రిశూలం మరియు గంట చిత్రం"),
        "prices": [(50100, 1500), (85100, 2500), (125100, 3500)],
        "addons": [("addon-flowers", 10100, 300, 3, False,
                    alt("Bilva and flower garland", "बिल्व और फूलों की माला", "வில்வம் மற்றும் பூமாலை", "బిల్వ పత్రాలు మరియు పూలమాల"))],
        "events": [(2, 7, 0), (9, 7, 0), (16, 7, 0)],
        "tr": {
            "en": T("Rudrabhishekam", "Abhishekam of the Shiva lingam with the chanting of Sri Rudram", "Monday special",
                    "Rudrabhishekam is the bathing of the Shiva lingam with milk, curd, honey, ghee and sacred water while the priests chant the Sri Rudram from the Krishna Yajurveda.\n\nThe sankalp is taken in the names and gotra you give us, before the abhishekam begins.",
                    [("Traditional purpose", "Offered to Shiva for peace of mind within the family."),
                     ("Ritual of purification", "The abhishekam is traditionally performed to cleanse and renew."),
                     ("For elders", "Often booked by children on behalf of their parents.")],
                    [("Sankalp", "The priest takes the sankalp in each devotee's name and gotra.", 0),
                     ("Ganapati puja", "A short invocation of Ganapati before the main ritual.", 0),
                     ("Rudrabhishekam", "Eleven rounds of Sri Rudram with the abhishekam.", 1),
                     ("Archana and aarti", "Bilva archana followed by the closing aarti.", 0)],
                    [("Do I need to be present?", "No. The priests take the sankalp in your name and you receive the video on WhatsApp."),
                     ("Can I add my parents' names?", "Yes. Choose the Couple or Family package to add more names.")],
                    "Rudrabhishekam at Sri Mallikarjuna Swamy Temple, Vijayawada",
                    "Book Rudrabhishekam with sankalp in your name and gotra. Video proof on WhatsApp."),
            "hi": T("रुद्राभिषेक", "श्री रुद्रम के पाठ के साथ शिवलिंग का अभिषेक", "सोमवार विशेष",
                    "रुद्राभिषेक में शिवलिंग को दूध, दही, शहद, घी और पवित्र जल से स्नान कराया जाता है, जबकि पुजारी कृष्ण यजुर्वेद का श्री रुद्रम पढ़ते हैं।\n\nअभिषेक से पहले आपके दिए नाम और गोत्र से संकल्प लिया जाता है।",
                    [("पारंपरिक उद्देश्य", "परिवार में मन की शांति के लिए शिव को अर्पित।"),
                     ("शुद्धि का अनुष्ठान", "अभिषेक परंपरागत रूप से शुद्धि और नवीनता के लिए किया जाता है।"),
                     ("बुज़ुर्गों के लिए", "अक्सर बच्चे अपने माता-पिता की ओर से बुक करते हैं।")],
                    [("संकल्प", "पुजारी हर भक्त के नाम और गोत्र से संकल्प लेते हैं।", 0),
                     ("गणपति पूजा", "मुख्य अनुष्ठान से पहले गणपति का संक्षिप्त आवाहन।", 0),
                     ("रुद्राभिषेक", "अभिषेक के साथ श्री रुद्रम के ग्यारह पाठ।", 1),
                     ("अर्चना और आरती", "बिल्व अर्चना और फिर समापन आरती।", 0)],
                    [("क्या मुझे उपस्थित रहना होगा?", "नहीं। पुजारी आपके नाम से संकल्प लेते हैं और वीडियो WhatsApp पर मिलता है।"),
                     ("क्या मैं माता-पिता के नाम जोड़ सकता हूँ?", "हाँ। अधिक नामों के लिए दंपति या परिवार पैकेज चुनें।")],
                    "रुद्राभिषेक, श्री मल्लिकार्जुन स्वामी मंदिर, विजयवाड़ा",
                    "अपने नाम और गोत्र से संकल्प के साथ रुद्राभिषेक बुक करें। WhatsApp पर वीडियो।"),
            "ta": T("ருத்ராபிஷேகம்", "ஸ்ரீ ருத்ரம் பாராயணத்துடன் சிவலிங்க அபிஷேகம்", "திங்கள் சிறப்பு",
                    "ருத்ராபிஷேகத்தில் அர்ச்சகர்கள் கிருஷ்ண யஜுர்வேதத்தின் ஸ்ரீ ருத்ரத்தை ஓதும்போது சிவலிங்கத்திற்கு பால், தயிர், தேன், நெய் மற்றும் புனித நீரால் அபிஷேகம் செய்யப்படுகிறது.\n\nஅபிஷேகத்திற்கு முன் நீங்கள் கொடுக்கும் பெயர் மற்றும் கோத்திரத்தில் சங்கல்பம் செய்யப்படுகிறது.",
                    [("பாரம்பரிய நோக்கம்", "குடும்பத்தில் மன அமைதிக்காக சிவனுக்கு அர்ப்பணிக்கப்படுகிறது."),
                     ("சுத்திகரிப்புச் சடங்கு", "அபிஷேகம் பாரம்பரியமாக சுத்திகரிப்புக்காகச் செய்யப்படுகிறது."),
                     ("பெரியவர்களுக்காக", "பிள்ளைகள் பெற்றோருக்காக அடிக்கடி முன்பதிவு செய்கிறார்கள்.")],
                    [("சங்கல்பம்", "ஒவ்வொரு பக்தரின் பெயர் மற்றும் கோத்திரத்தில் சங்கல்பம்.", 0),
                     ("கணபதி பூஜை", "முக்கிய சடங்கிற்கு முன் கணபதி ஆவாஹனம்.", 0),
                     ("ருத்ராபிஷேகம்", "அபிஷேகத்துடன் பதினொரு முறை ஸ்ரீ ருத்ர பாராயணம்.", 1),
                     ("அர்ச்சனை மற்றும் ஆரத்தி", "வில்வ அர்ச்சனை, பின்னர் நிறைவு ஆரத்தி.", 0)],
                    [("நான் நேரில் இருக்க வேண்டுமா?", "இல்லை. அர்ச்சகர்கள் உங்கள் பெயரில் சங்கல்பம் செய்வார்கள்; காணொளி WhatsApp இல் வரும்."),
                     ("பெற்றோர் பெயர்களைச் சேர்க்கலாமா?", "ஆம். தம்பதி அல்லது குடும்பத் தொகுப்பைத் தேர்ந்தெடுக்கவும்.")],
                    "ருத்ராபிஷேகம், ஸ்ரீ மல்லிகார்ஜுன ஸ்வாமி கோவில், விஜயவாடா",
                    "உங்கள் பெயர் மற்றும் கோத்திரத்தில் சங்கல்பத்துடன் ருத்ராபிஷேகம் முன்பதிவு செய்யுங்கள்."),
            "te": T("రుద్రాభిషేకం", "శ్రీ రుద్రం పఠనంతో శివలింగ అభిషేకం", "సోమవారం ప్రత్యేకం",
                    "రుద్రాభిషేకంలో అర్చకులు కృష్ణ యజుర్వేదంలోని శ్రీ రుద్రం పఠిస్తుండగా శివలింగానికి పాలు, పెరుగు, తేనె, నెయ్యి మరియు పవిత్ర జలంతో అభిషేకం చేస్తారు.\n\nఅభిషేకానికి ముందు మీరు ఇచ్చిన పేర్లు మరియు గోత్రంతో సంకల్పం చేస్తారు.",
                    [("సాంప్రదాయ ఉద్దేశం", "కుటుంబంలో మనశ్శాంతి కోసం శివునికి సమర్పించేది."),
                     ("శుద్ధి క్రతువు", "అభిషేకం సంప్రదాయంగా శుద్ధి కోసం చేస్తారు."),
                     ("పెద్దల కోసం", "తరచుగా పిల్లలు తల్లిదండ్రుల తరఫున బుక్ చేస్తారు.")],
                    [("సంకల్పం", "ప్రతి భక్తుని పేరు మరియు గోత్రంతో సంకల్పం.", 0),
                     ("గణపతి పూజ", "ప్రధాన క్రతువుకు ముందు గణపతి ఆవాహన.", 0),
                     ("రుద్రాభిషేకం", "అభిషేకంతో పాటు పదకొండు సార్లు శ్రీ రుద్ర పఠనం.", 1),
                     ("అర్చన మరియు హారతి", "బిల్వ అర్చన, తర్వాత ముగింపు హారతి.", 0)],
                    [("నేను హాజరు కావాలా?", "అవసరం లేదు. అర్చకులు మీ పేరుతో సంకల్పం చేస్తారు; వీడియో WhatsAppలో వస్తుంది."),
                     ("తల్లిదండ్రుల పేర్లు చేర్చవచ్చా?", "అవును. మరిన్ని పేర్ల కోసం దంపతులు లేదా కుటుంబ ప్యాకేజీ ఎంచుకోండి.")],
                    "రుద్రాభిషేకం, శ్రీ మల్లికార్జున స్వామి ఆలయం, విజయవాడ",
                    "మీ పేరు మరియు గోత్రంతో సంకల్పంతో రుద్రాభిషేకం బుక్ చేయండి. WhatsAppలో వీడియో."),
        },
    },
    {
        "key": "navagraha", "temple": 1, "kind": "one_time", "slug": "navagraha-shanti-homam",
        "deity_tags": ["navagraha"], "dosha_tags": ["navagraha"], "benefit_tags": ["harmony"],
        "tradition": "Smarta Vedic", "duration_minutes": 150, "priests_count": 5, "sankalp_language": "Sanskrit",
        "requires_nakshatra": True, "video_sla_hours": 36, "deliverables": ["sankalp_clip", "full_video", "photos"],
        "prasad_box": ["vibhuti", "akshata", "raksha_sutra", "dry_prasad"],
        "images": ["navagraha", "navagraha-2"],
        "image_alt": alt("Nine circles around a gold centre", "सुनहरे केंद्र के चारों ओर नौ वृत्त",
                         "தங்க மையத்தைச் சுற்றி ஒன்பது வட்டங்கள்", "బంగారు కేంద్రం చుట్టూ తొమ్మిది వృత్తాలు"),
        "prices": [(110100, 3100), (165100, 4500), (210100, 5900)],
        "addons": [("addon-diya", 5100, 200, 5, False,
                    alt("Ghee lamp offering", "घी का दीपक", "நெய் விளக்கு", "నెయ్యి దీపం")),
                   ("addon-coconut", 15100, 500, 1, True,
                    alt("Blessed coconut sent home", "घर भेजा जाने वाला अभिमंत्रित नारियल", "வீட்டுக்கு அனுப்பப்படும் தேங்காய்", "ఇంటికి పంపే నారికేళం"))],
        "events": [(1, 6, 30), (8, 6, 30), (22, 6, 30)],
        "tr": {
            "en": T("Navagraha Shanti Homam", "A homam to the nine planetary deities, with a mantra for each graha", "Sankranti",
                    "The Navagraha Shanti Homam offers ahutis to each of the nine grahas, from Surya to Ketu, in a single fire altar. Five ritviks chant the mantra of each graha in turn.\n\nBecause the homam is tied to your birth star, the nakshatra is required for each name.",
                    [("Traditional purpose", "Performed to seek harmony with the nine grahas."),
                     ("Before new beginnings", "Commonly done before a new job, home or journey."),
                     ("One homam, nine grahas", "Each graha receives its own mantra and ahuti.")],
                    [("Sankalp with nakshatra", "Names, gotra and nakshatra are read out.", 0),
                     ("Kalasha sthapana", "Nine kalashas are set up, one per graha.", 0),
                     ("Navagraha homam", "Ahutis to each graha with its mantra.", 1),
                     ("Purnahuti", "The final offering into the fire, then aarti.", 0)],
                    [("Why is the nakshatra required?", "The graha mantras are recited for your birth star, so the priest needs it for the sankalp."),
                     ("Is this a temple?", "No. It is a yagashala, a dedicated space for fire rituals.")],
                    "Navagraha Shanti Homam in Kanchipuram",
                    "Book a Navagraha Shanti Homam with sankalp in your name, gotra and nakshatra. Video on WhatsApp."),
            "hi": T("नवग्रह शांति होम", "नौ ग्रह देवताओं के लिए होम, हर ग्रह के मंत्र के साथ", "संक्रांति",
                    "नवग्रह शांति होम में सूर्य से केतु तक नौ ग्रहों को एक ही अग्निकुंड में आहुति दी जाती है। पाँच ऋत्विक बारी-बारी से हर ग्रह का मंत्र पढ़ते हैं।\n\nयह होम जन्म नक्षत्र से जुड़ा है, इसलिए हर नाम के लिए नक्षत्र आवश्यक है।",
                    [("पारंपरिक उद्देश्य", "नौ ग्रहों के साथ सामंजस्य की कामना से किया जाता है।"),
                     ("नई शुरुआत से पहले", "नई नौकरी, घर या यात्रा से पहले प्रायः किया जाता है।"),
                     ("एक होम, नौ ग्रह", "हर ग्रह को अपना मंत्र और आहुति मिलती है।")],
                    [("नक्षत्र सहित संकल्प", "नाम, गोत्र और नक्षत्र पढ़े जाते हैं।", 0),
                     ("कलश स्थापना", "हर ग्रह के लिए एक, नौ कलश स्थापित होते हैं।", 0),
                     ("नवग्रह होम", "हर ग्रह को उसके मंत्र के साथ आहुति।", 1),
                     ("पूर्णाहुति", "अग्नि में अंतिम आहुति, फिर आरती।", 0)],
                    [("नक्षत्र क्यों आवश्यक है?", "ग्रह मंत्र आपके जन्म नक्षत्र के लिए पढ़े जाते हैं, इसलिए संकल्प में यह चाहिए।"),
                     ("क्या यह मंदिर है?", "नहीं। यह यज्ञशाला है, अग्नि अनुष्ठानों के लिए समर्पित स्थान।")],
                    "नवग्रह शांति होम, कांचीपुरम",
                    "अपने नाम, गोत्र और नक्षत्र से संकल्प के साथ नवग्रह शांति होम बुक करें।"),
            "ta": T("நவக்கிரக சாந்தி ஹோமம்", "ஒவ்வொரு கிரகத்திற்கும் மந்திரத்துடன் ஒன்பது கிரக தேவதைகளுக்கான ஹோமம்", "சங்கராந்தி",
                    "நவக்கிரக சாந்தி ஹோமத்தில் சூரியன் முதல் கேது வரை ஒன்பது கிரகங்களுக்கும் ஒரே ஹோம குண்டத்தில் ஆகுதி அளிக்கப்படுகிறது. ஐந்து ரித்விக்குகள் ஒவ்வொரு கிரகத்தின் மந்திரத்தையும் ஓதுகிறார்கள்.\n\nஇந்த ஹோமம் ஜன்ம நட்சத்திரத்துடன் தொடர்புடையதால் ஒவ்வொரு பெயருக்கும் நட்சத்திரம் தேவை.",
                    [("பாரம்பரிய நோக்கம்", "ஒன்பது கிரகங்களுடன் இணக்கம் வேண்டிச் செய்யப்படுகிறது."),
                     ("புதிய தொடக்கங்களுக்கு முன்", "புதிய வேலை, வீடு அல்லது பயணத்திற்கு முன் செய்யப்படுகிறது."),
                     ("ஒரு ஹோமம், ஒன்பது கிரகங்கள்", "ஒவ்வொரு கிரகத்திற்கும் தனி மந்திரமும் ஆகுதியும்.")],
                    [("நட்சத்திரத்துடன் சங்கல்பம்", "பெயர், கோத்திரம், நட்சத்திரம் வாசிக்கப்படுகின்றன.", 0),
                     ("கலச ஸ்தாபனம்", "ஒவ்வொரு கிரகத்திற்கும் ஒன்றாக ஒன்பது கலசங்கள்.", 0),
                     ("நவக்கிரக ஹோமம்", "ஒவ்வொரு கிரகத்திற்கும் மந்திரத்துடன் ஆகுதி.", 1),
                     ("பூர்ணாஹுதி", "அக்னியில் இறுதி ஆகுதி, பின்னர் ஆரத்தி.", 0)],
                    [("நட்சத்திரம் ஏன் தேவை?", "கிரக மந்திரங்கள் உங்கள் ஜன்ம நட்சத்திரத்திற்காக ஓதப்படுவதால் சங்கல்பத்தில் அது தேவை."),
                     ("இது கோவிலா?", "இல்லை. இது அக்னிச் சடங்குகளுக்கான யாகசாலை.")],
                    "நவக்கிரக சாந்தி ஹோமம், காஞ்சிபுரம்",
                    "உங்கள் பெயர், கோத்திரம், நட்சத்திரத்துடன் நவக்கிரக சாந்தி ஹோமம் முன்பதிவு செய்யுங்கள்."),
            "te": T("నవగ్రహ శాంతి హోమం", "ప్రతి గ్రహానికి మంత్రంతో తొమ్మిది గ్రహ దేవతలకు హోమం", "సంక్రాంతి",
                    "నవగ్రహ శాంతి హోమంలో సూర్యుని నుండి కేతువు వరకు తొమ్మిది గ్రహాలకు ఒకే హోమ కుండంలో ఆహుతులు సమర్పిస్తారు. ఐదుగురు ఋత్విక్కులు ప్రతి గ్రహ మంత్రాన్ని పఠిస్తారు.\n\nఈ హోమం జన్మ నక్షత్రంతో ముడిపడి ఉన్నందున ప్రతి పేరుకు నక్షత్రం అవసరం.",
                    [("సాంప్రదాయ ఉద్దేశం", "తొమ్మిది గ్రహాలతో సామరస్యం కోరుతూ చేస్తారు."),
                     ("కొత్త ప్రారంభాలకు ముందు", "కొత్త ఉద్యోగం, ఇల్లు లేదా ప్రయాణానికి ముందు చేస్తారు."),
                     ("ఒక హోమం, తొమ్మిది గ్రహాలు", "ప్రతి గ్రహానికి ప్రత్యేక మంత్రం మరియు ఆహుతి.")],
                    [("నక్షత్రంతో సంకల్పం", "పేరు, గోత్రం, నక్షత్రం చదువుతారు.", 0),
                     ("కలశ స్థాపన", "ప్రతి గ్రహానికి ఒకటి చొప్పున తొమ్మిది కలశాలు.", 0),
                     ("నవగ్రహ హోమం", "ప్రతి గ్రహానికి మంత్రంతో ఆహుతి.", 1),
                     ("పూర్ణాహుతి", "అగ్నిలో చివరి ఆహుతి, తర్వాత హారతి.", 0)],
                    [("నక్షత్రం ఎందుకు అవసరం?", "గ్రహ మంత్రాలు మీ జన్మ నక్షత్రం కోసం పఠిస్తారు, కాబట్టి సంకల్పంలో అది కావాలి."),
                     ("ఇది ఆలయమా?", "కాదు. ఇది అగ్ని క్రతువుల కోసం ప్రత్యేకమైన యాగశాల.")],
                    "నవగ్రహ శాంతి హోమం, కాంచీపురం",
                    "మీ పేరు, గోత్రం, నక్షత్రంతో సంకల్పంతో నవగ్రహ శాంతి హోమం బుక్ చేయండి."),
        },
    },
    {
        "key": "pitru-tarpan", "temple": 2, "kind": "one_time", "slug": "pitru-tarpan",
        "deity_tags": ["ganga"], "dosha_tags": ["pitru"], "benefit_tags": ["ancestors"],
        "tradition": "Vedic Shrauta", "duration_minutes": 60, "priests_count": 2, "sankalp_language": "Hindi",
        "requires_nakshatra": False, "deliverables": ["sankalp_clip", "full_video"], "prasad_box": None,
        "images": ["pitru-tarpan", "pitru-tarpan-2"],
        "image_alt": alt("River waves and a lamp", "नदी की लहरें और दीपक", "நதி அலைகளும் விளக்கும்", "నది అలలు మరియు దీపం"),
        "prices": [(75100, 2100), (110100, 3100), (151100, 4100)],
        "addons": [],
        "events": [(3, 8, 0), (17, 8, 0)],
        "locales": ["en", "hi", "te"],
        "tr": {
            "en": T("Pitru Tarpan at Dashashwamedh Ghat", "Offerings of water and sesame to ancestors on the Ganga", "Pitru Paksha",
                    "Tarpan is the offering of water mixed with black sesame to one's ancestors. At the ghat, the purohit recites the names of three generations on both sides of the family.\n\nPlease give the names of the ancestors in the wish field if you would like them to be read.",
                    [("Traditional purpose", "An act of remembrance and gratitude to one's ancestors."),
                     ("Pitru Paksha", "Traditionally performed during the fortnight of the ancestors."),
                     ("Performed on the Ganga", "Offered on the steps of an ancient ghat.")],
                    [("Sankalp", "The family's names and gotra are read out.", 0),
                     ("Tarpan", "Water with sesame is offered to each ancestor.", 1),
                     ("Pinda daan", "Rice offerings are placed and immersed.", 0)],
                    [("Can I include ancestors' names?", "Yes. Write them in the wish field and the purohit will read them."),
                     ("Is there prasad?", "No prasad is sent for tarpan, by tradition.")],
                    "Pitru Tarpan at Dashashwamedh Ghat, Varanasi",
                    "Book Pitru Tarpan on the Ganga in Varanasi, with sankalp in your family's names."),
            "hi": T("दशाश्वमेध घाट पर पितृ तर्पण", "गंगा तट पर पूर्वजों को जल और तिल का अर्पण", "पितृ पक्ष",
                    "तर्पण में काले तिल मिला जल पूर्वजों को अर्पित किया जाता है। घाट पर पुरोहित परिवार के दोनों पक्षों की तीन पीढ़ियों के नाम पढ़ते हैं।\n\nयदि आप चाहते हैं कि पूर्वजों के नाम पढ़े जाएँ, तो उन्हें इच्छा वाले खाने में लिखें।",
                    [("पारंपरिक उद्देश्य", "पूर्वजों के प्रति स्मरण और कृतज्ञता का कर्म।"),
                     ("पितृ पक्ष", "परंपरागत रूप से पितरों के पखवाड़े में किया जाता है।"),
                     ("गंगा तट पर", "एक प्राचीन घाट की सीढ़ियों पर अर्पित।")],
                    [("संकल्प", "परिवार के नाम और गोत्र पढ़े जाते हैं।", 0),
                     ("तर्पण", "हर पूर्वज को तिल मिला जल अर्पित।", 1),
                     ("पिंड दान", "चावल के पिंड रखे और विसर्जित किए जाते हैं।", 0)],
                    [("क्या पूर्वजों के नाम शामिल कर सकते हैं?", "हाँ। इच्छा वाले खाने में लिखें, पुरोहित उन्हें पढ़ेंगे।"),
                     ("क्या प्रसाद मिलता है?", "परंपरा के अनुसार तर्पण का प्रसाद नहीं भेजा जाता।")],
                    "दशाश्वमेध घाट पर पितृ तर्पण, वाराणसी",
                    "वाराणसी में गंगा तट पर अपने परिवार के नाम से पितृ तर्पण बुक करें।"),
            "te": T("దశాశ్వమేధ ఘాట్‌లో పితృ తర్పణం", "గంగా తీరంలో పూర్వీకులకు జలం మరియు నువ్వుల సమర్పణ", "పితృ పక్షం",
                    "తర్పణంలో నల్ల నువ్వులు కలిపిన జలాన్ని పూర్వీకులకు సమర్పిస్తారు. ఘాట్‌లో పురోహితులు కుటుంబంలో రెండు వైపులా మూడు తరాల పేర్లు చదువుతారు.\n\nపూర్వీకుల పేర్లు చదవాలని కోరుకుంటే, వాటిని కోరిక విభాగంలో రాయండి.",
                    [("సాంప్రదాయ ఉద్దేశం", "పూర్వీకుల పట్ల స్మరణ మరియు కృతజ్ఞత."),
                     ("పితృ పక్షం", "సంప్రదాయంగా పితృ పక్షంలో చేస్తారు."),
                     ("గంగా తీరంలో", "ప్రాచీన ఘాట్ మెట్లపై సమర్పణ.")],
                    [("సంకల్పం", "కుటుంబ పేర్లు మరియు గోత్రం చదువుతారు.", 0),
                     ("తర్పణం", "ప్రతి పూర్వీకునికి నువ్వుల జలం సమర్పణ.", 1),
                     ("పిండ ప్రదానం", "అన్న పిండాలు సమర్పించి నిమజ్జనం చేస్తారు.", 0)],
                    [("పూర్వీకుల పేర్లు చేర్చవచ్చా?", "అవును. కోరిక విభాగంలో రాయండి, పురోహితులు చదువుతారు."),
                     ("ప్రసాదం వస్తుందా?", "సంప్రదాయం ప్రకారం తర్పణానికి ప్రసాదం పంపరు.")],
                    "దశాశ్వమేధ ఘాట్‌లో పితృ తర్పణం, వారణాసి",
                    "వారణాసిలో గంగా తీరంలో మీ కుటుంబ పేర్లతో పితృ తర్పణం బుక్ చేయండి."),
        },
    },
    {
        "key": "lakshmi-kubera", "temple": 3, "kind": "one_time", "slug": "lakshmi-kubera-puja",
        "deity_tags": ["lakshmi"], "dosha_tags": [], "benefit_tags": ["prosperity"],
        "tradition": "Pancharatra", "duration_minutes": 75, "priests_count": 2, "sankalp_language": "Telugu",
        "requires_nakshatra": False, "deliverables": ["sankalp_clip", "full_video", "photos"],
        "prasad_box": ["kumkum", "akshata", "dry_prasad"], "images": ["lakshmi-kubera", "lakshmi-kubera-2"],
        "image_alt": alt("Lotus and kalash illustration", "कमल और कलश का चित्र", "தாமரை மற்றும் கலசத்தின் ஓவியம்", "కమలం మరియు కలశం చిత్రం"),
        "prices": [(60100, 1800), (95100, 2700), (135100, 3700)],
        "addons": [("addon-flowers", 10100, 300, 3, False,
                    alt("Lotus flowers for archana", "अर्चना के लिए कमल", "அர்ச்சனைக்குத் தாமரைப் பூக்கள்", "అర్చన కోసం కమలాలు"))],
        "events": [(4, 18, 0), (11, 18, 0), (25, 18, 0)],
        "tr": {
            "en": T("Lakshmi Kubera Puja", "Kumkumarchana to Mahalakshmi and invocation of Kubera on a Friday evening", "Friday",
                    "Mahalakshmi is worshipped with the 108 names and kumkum, followed by an invocation of Kubera, keeper of the wealth of the devas.\n\nThe puja is performed on a Friday evening in the temple's main mandapam.",
                    [("Traditional purpose", "Performed to seek Lakshmi's blessings for the household."),
                     ("Friday worship", "Fridays are traditionally dedicated to Lakshmi."),
                     ("Kumkumarchana", "Kumkum from the archana is sent home with prasad.")],
                    [("Sankalp", "Names and gotra are read before the archana.", 0),
                     ("Lakshmi ashtottara", "Kumkumarchana with the 108 names.", 1),
                     ("Kubera puja", "Invocation of Kubera with the Kubera mantra.", 0),
                     ("Aarti", "Closing aarti with a ghee lamp.", 0)],
                    [("When is it performed?", "On the Friday evening shown on this page, in IST."),
                     ("What prasad do I receive?", "Kumkum, akshata and dry prasad, if you add delivery.")],
                    "Lakshmi Kubera Puja at Sri Mahalakshmi Temple, Hyderabad",
                    "Book a Friday Lakshmi Kubera Puja with sankalp in your name. Video on WhatsApp."),
            "hi": T("लक्ष्मी कुबेर पूजा", "शुक्रवार की शाम महालक्ष्मी की कुमकुमार्चना और कुबेर का आवाहन", "शुक्रवार",
                    "महालक्ष्मी की 108 नामों और कुमकुम से पूजा होती है, फिर देवताओं के धन के रक्षक कुबेर का आवाहन किया जाता है।\n\nपूजा शुक्रवार शाम मंदिर के मुख्य मंडप में होती है।",
                    [("पारंपरिक उद्देश्य", "घर के लिए लक्ष्मी के आशीर्वाद की कामना से किया जाता है।"),
                     ("शुक्रवार पूजा", "शुक्रवार परंपरागत रूप से लक्ष्मी को समर्पित है।"),
                     ("कुमकुमार्चना", "अर्चना का कुमकुम प्रसाद के साथ घर भेजा जाता है।")],
                    [("संकल्प", "अर्चना से पहले नाम और गोत्र पढ़े जाते हैं।", 0),
                     ("लक्ष्मी अष्टोत्तर", "108 नामों से कुमकुमार्चना।", 1),
                     ("कुबेर पूजा", "कुबेर मंत्र से कुबेर का आवाहन।", 0),
                     ("आरती", "घी के दीपक से समापन आरती।", 0)],
                    [("पूजा कब होती है?", "इस पेज पर दिखाए गए शुक्रवार की शाम, IST में।"),
                     ("कौन-सा प्रसाद मिलेगा?", "डिलीवरी जोड़ने पर कुमकुम, अक्षत और सूखा प्रसाद।")],
                    "लक्ष्मी कुबेर पूजा, श्री महालक्ष्मी मंदिर, हैदराबाद",
                    "अपने नाम से संकल्प के साथ शुक्रवार की लक्ष्मी कुबेर पूजा बुक करें।"),
            "ta": T("லட்சுமி குபேர பூஜை", "வெள்ளி மாலை மகாலட்சுமிக்குக் குங்குமார்ச்சனை மற்றும் குபேர ஆவாஹனம்", "வெள்ளிக்கிழமை",
                    "மகாலட்சுமி 108 நாமங்கள் மற்றும் குங்குமத்தால் வழிபடப்படுகிறார்; பின்னர் தேவர்களின் செல்வக் காவலரான குபேரன் ஆவாஹனம் செய்யப்படுகிறார்.\n\nபூஜை வெள்ளிக்கிழமை மாலை கோவிலின் முக்கிய மண்டபத்தில் நடைபெறும்.",
                    [("பாரம்பரிய நோக்கம்", "இல்லத்திற்கு லட்சுமியின் அருள் வேண்டிச் செய்யப்படுகிறது."),
                     ("வெள்ளிக்கிழமை வழிபாடு", "வெள்ளிக்கிழமை பாரம்பரியமாக லட்சுமிக்குரியது."),
                     ("குங்குமார்ச்சனை", "அர்ச்சனைக் குங்குமம் பிரசாதத்துடன் வீட்டுக்கு அனுப்பப்படும்.")],
                    [("சங்கல்பம்", "அர்ச்சனைக்கு முன் பெயரும் கோத்திரமும் வாசிக்கப்படும்.", 0),
                     ("லட்சுமி அஷ்டோத்தரம்", "108 நாமங்களுடன் குங்குமார்ச்சனை.", 1),
                     ("குபேர பூஜை", "குபேர மந்திரத்துடன் ஆவாஹனம்.", 0),
                     ("ஆரத்தி", "நெய் விளக்குடன் நிறைவு ஆரத்தி.", 0)],
                    [("பூஜை எப்போது?", "இந்தப் பக்கத்தில் காட்டப்படும் வெள்ளி மாலை, IST நேரத்தில்."),
                     ("என்ன பிரசாதம் கிடைக்கும்?", "டெலிவரி சேர்த்தால் குங்குமம், அட்சதை மற்றும் உலர் பிரசாதம்.")],
                    "லட்சுமி குபேர பூஜை, ஸ்ரீ மகாலட்சுமி கோவில், ஹைதராபாத்",
                    "உங்கள் பெயரில் சங்கல்பத்துடன் வெள்ளிக்கிழமை லட்சுமி குபேர பூஜை முன்பதிவு செய்யுங்கள்."),
            "te": T("లక్ష్మీ కుబేర పూజ", "శుక్రవారం సాయంత్రం మహాలక్ష్మికి కుంకుమార్చన మరియు కుబేర ఆవాహన", "శుక్రవారం",
                    "మహాలక్ష్మిని 108 నామాలు మరియు కుంకుమతో పూజిస్తారు; తర్వాత దేవతల సంపద రక్షకుడైన కుబేరుని ఆవాహన చేస్తారు.\n\nపూజ శుక్రవారం సాయంత్రం ఆలయ ప్రధాన మండపంలో జరుగుతుంది.",
                    [("సాంప్రదాయ ఉద్దేశం", "ఇంటికి లక్ష్మీ అనుగ్రహం కోరుతూ చేస్తారు."),
                     ("శుక్రవార పూజ", "శుక్రవారం సంప్రదాయంగా లక్ష్మికి అంకితం."),
                     ("కుంకుమార్చన", "అర్చన కుంకుమ ప్రసాదంతో ఇంటికి పంపుతారు.")],
                    [("సంకల్పం", "అర్చనకు ముందు పేరు మరియు గోత్రం చదువుతారు.", 0),
                     ("లక్ష్మీ అష్టోత్తరం", "108 నామాలతో కుంకుమార్చన.", 1),
                     ("కుబేర పూజ", "కుబేర మంత్రంతో ఆవాహన.", 0),
                     ("హారతి", "నెయ్యి దీపంతో ముగింపు హారతి.", 0)],
                    [("పూజ ఎప్పుడు?", "ఈ పేజీలో చూపిన శుక్రవారం సాయంత్రం, IST సమయంలో."),
                     ("ఏ ప్రసాదం వస్తుంది?", "డెలివరీ జోడిస్తే కుంకుమ, అక్షతలు మరియు పొడి ప్రసాదం.")],
                    "లక్ష్మీ కుబేర పూజ, శ్రీ మహాలక్ష్మి ఆలయం, హైదరాబాద్",
                    "మీ పేరుతో సంకల్పంతో శుక్రవారం లక్ష్మీ కుబేర పూజ బుక్ చేయండి."),
        },
    },
    {
        "key": "rahu-ketu", "temple": 1, "kind": "one_time", "slug": "rahu-ketu-shanti-puja",
        "deity_tags": ["navagraha"], "dosha_tags": ["rahu_ketu"], "benefit_tags": ["harmony"],
        "tradition": "Smarta Vedic", "duration_minutes": 90, "priests_count": 3, "sankalp_language": "Tamil",
        "requires_nakshatra": True, "deliverables": ["sankalp_clip", "full_video"], "prasad_box": ["vibhuti", "raksha_sutra"],
        "images": ["rahu-ketu"],
        "image_alt": alt("Planetary circles in gold", "सुनहरे ग्रह-वृत्त", "தங்க நிற கிரக வட்டங்கள்", "బంగారు గ్రహ వృత్తాలు"),
        "prices": [(65100, 1900), (99100, 2800), (139100, 3800)],
        "addons": [], "events": [(6, 9, 0), (13, 9, 0)],
        "tr": {
            "en": T("Rahu Ketu Shanti Puja", "Puja to Rahu and Ketu with japa and homam", "Rahu kalam",
                    "Rahu and Ketu are worshipped with their japa and a small homam during Rahu kalam. The priests recite the mantras for each name in the booking.",
                    [("Traditional purpose", "Performed when a horoscope indicates Rahu–Ketu dosha."),
                     ("During Rahu kalam", "Timed to the traditional Rahu kalam window."),
                     ("Japa and homam", "Both mantra japa and fire offerings.")],
                    [("Sankalp", "Names, gotra and nakshatra are read.", 0),
                     ("Rahu Ketu japa", "Japa of the Rahu and Ketu mantras.", 1),
                     ("Homam", "Ahutis for Rahu and Ketu.", 0)],
                    [("Do I need my horoscope?", "No. Your nakshatra is enough for the sankalp.")],
                    "Rahu Ketu Shanti Puja in Kanchipuram",
                    "Book a Rahu Ketu Shanti Puja with sankalp in your name, gotra and nakshatra."),
            "hi": T("राहु केतु शांति पूजा", "जप और होम के साथ राहु और केतु की पूजा", "राहु काल",
                    "राहु काल में जप और छोटे होम के साथ राहु और केतु की पूजा होती है। पुजारी बुकिंग के हर नाम के लिए मंत्र पढ़ते हैं।",
                    [("पारंपरिक उद्देश्य", "जब कुंडली में राहु–केतु दोष बताया गया हो।"),
                     ("राहु काल में", "पारंपरिक राहु काल के समय पर।"),
                     ("जप और होम", "मंत्र जप और अग्नि आहुति दोनों।")],
                    [("संकल्प", "नाम, गोत्र और नक्षत्र पढ़े जाते हैं।", 0),
                     ("राहु केतु जप", "राहु और केतु मंत्रों का जप।", 1),
                     ("होम", "राहु और केतु के लिए आहुतियाँ।", 0)],
                    [("क्या कुंडली चाहिए?", "नहीं। संकल्प के लिए आपका नक्षत्र पर्याप्त है।")],
                    "राहु केतु शांति पूजा, कांचीपुरम",
                    "अपने नाम, गोत्र और नक्षत्र से संकल्प के साथ राहु केतु शांति पूजा बुक करें।"),
            "ta": T("ராகு கேது சாந்தி பூஜை", "ஜபம் மற்றும் ஹோமத்துடன் ராகு கேது பூஜை", "ராகு காலம்",
                    "ராகு காலத்தில் ஜபம் மற்றும் சிறிய ஹோமத்துடன் ராகு கேது வழிபடப்படுகிறார்கள். முன்பதிவில் உள்ள ஒவ்வொரு பெயருக்கும் அர்ச்சகர்கள் மந்திரம் ஓதுகிறார்கள்.",
                    [("பாரம்பரிய நோக்கம்", "ஜாதகத்தில் ராகு–கேது தோஷம் குறிப்பிடப்படும்போது செய்யப்படுகிறது."),
                     ("ராகு காலத்தில்", "பாரம்பரிய ராகு கால நேரத்தில்."),
                     ("ஜபமும் ஹோமமும்", "மந்திர ஜபம் மற்றும் அக்னி ஆகுதி இரண்டும்.")],
                    [("சங்கல்பம்", "பெயர், கோத்திரம், நட்சத்திரம் வாசிக்கப்படும்.", 0),
                     ("ராகு கேது ஜபம்", "ராகு, கேது மந்திர ஜபம்.", 1),
                     ("ஹோமம்", "ராகு, கேதுவுக்கு ஆகுதிகள்.", 0)],
                    [("ஜாதகம் தேவையா?", "இல்லை. சங்கல்பத்திற்கு உங்கள் நட்சத்திரம் போதும்.")],
                    "ராகு கேது சாந்தி பூஜை, காஞ்சிபுரம்",
                    "உங்கள் பெயர், கோத்திரம், நட்சத்திரத்துடன் ராகு கேது சாந்தி பூஜை முன்பதிவு செய்யுங்கள்."),
            "te": T("రాహు కేతు శాంతి పూజ", "జపం మరియు హోమంతో రాహు కేతు పూజ", "రాహు కాలం",
                    "రాహు కాలంలో జపం మరియు చిన్న హోమంతో రాహు కేతువులను పూజిస్తారు. బుకింగ్‌లోని ప్రతి పేరుకు అర్చకులు మంత్రాలు పఠిస్తారు.",
                    [("సాంప్రదాయ ఉద్దేశం", "జాతకంలో రాహు–కేతు దోషం సూచించినప్పుడు చేస్తారు."),
                     ("రాహు కాలంలో", "సాంప్రదాయ రాహు కాల సమయంలో."),
                     ("జపం మరియు హోమం", "మంత్ర జపం మరియు అగ్ని ఆహుతులు రెండూ.")],
                    [("సంకల్పం", "పేరు, గోత్రం, నక్షత్రం చదువుతారు.", 0),
                     ("రాహు కేతు జపం", "రాహు, కేతు మంత్ర జపం.", 1),
                     ("హోమం", "రాహు, కేతువులకు ఆహుతులు.", 0)],
                    [("జాతకం అవసరమా?", "అవసరం లేదు. సంకల్పానికి మీ నక్షత్రం చాలు.")],
                    "రాహు కేతు శాంతి పూజ, కాంచీపురం",
                    "మీ పేరు, గోత్రం, నక్షత్రంతో సంకల్పంతో రాహు కేతు శాంతి పూజ బుక్ చేయండి."),
        },
    },
    {
        "key": "satyanarayana", "temple": 3, "kind": "one_time", "slug": "satyanarayana-vratam",
        "deity_tags": ["vishnu"], "dosha_tags": [], "benefit_tags": ["family", "gratitude"],
        "tradition": "Vaishnava", "duration_minutes": 120, "priests_count": 2, "sankalp_language": "Telugu",
        "requires_nakshatra": False, "deliverables": ["sankalp_clip", "full_video", "photos"],
        "prasad_box": ["dry_prasad", "akshata"], "images": ["satyanarayana", "satyanarayana-2"],
        "image_alt": alt("Conch and kalash illustration", "शंख और कलश का चित्र", "சங்கு மற்றும் கலசத்தின் ஓவியம்", "శంఖం మరియు కలశం చిత్రం"),
        "prices": [(70100, 2000), (105100, 2900), (145100, 3900)],
        "addons": [], "events": [(5, 10, 0), (19, 10, 0)],
        "tr": {
            "en": T("Satyanarayana Vratam", "The full vratam with the five chapters of the katha, on Purnima", "Purnima",
                    "The Satyanarayana Vratam is performed on the full moon with the reading of the five chapters of the katha and the offering of sheera prasad.",
                    [("Traditional purpose", "Performed as an act of gratitude after a family milestone."),
                     ("On Purnima", "Traditionally observed on the full moon."),
                     ("Katha reading", "All five chapters are read aloud.")],
                    [("Sankalp", "The family's names and gotra are read.", 0),
                     ("Vratam puja", "Puja of Satyanarayana Swamy with tulsi.", 1),
                     ("Katha", "The five chapters of the vratam katha.", 0),
                     ("Aarti and prasad", "Aarti and offering of sheera prasad.", 0)],
                    [("Is this the full vratam?", "Yes. All five chapters of the katha are read.")],
                    "Satyanarayana Vratam on Purnima, Hyderabad",
                    "Book a Satyanarayana Vratam on Purnima with sankalp in your family's names."),
            "hi": T("सत्यनारायण व्रत", "पूर्णिमा पर कथा के पाँचों अध्यायों के साथ पूरा व्रत", "पूर्णिमा",
                    "सत्यनारायण व्रत पूर्णिमा के दिन कथा के पाँच अध्यायों के पाठ और शीरा प्रसाद के अर्पण के साथ किया जाता है।",
                    [("पारंपरिक उद्देश्य", "परिवार के किसी शुभ अवसर के बाद कृतज्ञता के रूप में।"),
                     ("पूर्णिमा पर", "परंपरागत रूप से पूर्णिमा को किया जाता है।"),
                     ("कथा पाठ", "पाँचों अध्याय पढ़े जाते हैं।")],
                    [("संकल्प", "परिवार के नाम और गोत्र पढ़े जाते हैं।", 0),
                     ("व्रत पूजा", "तुलसी से सत्यनारायण स्वामी की पूजा।", 1),
                     ("कथा", "व्रत कथा के पाँच अध्याय।", 0),
                     ("आरती और प्रसाद", "आरती और शीरा प्रसाद का अर्पण।", 0)],
                    [("क्या यह पूरा व्रत है?", "हाँ। कथा के पाँचों अध्याय पढ़े जाते हैं।")],
                    "पूर्णिमा पर सत्यनारायण व्रत, हैदराबाद",
                    "अपने परिवार के नाम से संकल्प के साथ पूर्णिमा का सत्यनारायण व्रत बुक करें।"),
            "ta": T("சத்யநாராயண விரதம்", "பௌர்ணமியில் கதையின் ஐந்து அத்தியாயங்களுடன் முழு விரதம்", "பௌர்ணமி",
                    "சத்யநாராயண விரதம் பௌர்ணமி அன்று கதையின் ஐந்து அத்தியாயங்களை வாசித்து, சீரா பிரசாதம் படைத்து செய்யப்படுகிறது.",
                    [("பாரம்பரிய நோக்கம்", "குடும்ப நல்ல நிகழ்வுக்குப் பின் நன்றியாகச் செய்யப்படுகிறது."),
                     ("பௌர்ணமியில்", "பாரம்பரியமாக பௌர்ணமி அன்று."),
                     ("கதை வாசிப்பு", "ஐந்து அத்தியாயங்களும் வாசிக்கப்படும்.")],
                    [("சங்கல்பம்", "குடும்பப் பெயர்களும் கோத்திரமும் வாசிக்கப்படும்.", 0),
                     ("விரத பூஜை", "துளசியுடன் சத்யநாராயண ஸ்வாமி பூஜை.", 1),
                     ("கதை", "விரதக் கதையின் ஐந்து அத்தியாயங்கள்.", 0),
                     ("ஆரத்தி மற்றும் பிரசாதம்", "ஆரத்தி, சீரா பிரசாதம் படைத்தல்.", 0)],
                    [("இது முழு விரதமா?", "ஆம். கதையின் ஐந்து அத்தியாயங்களும் வாசிக்கப்படும்.")],
                    "பௌர்ணமியில் சத்யநாராயண விரதம், ஹைதராபாத்",
                    "உங்கள் குடும்பப் பெயர்களில் சங்கல்பத்துடன் சத்யநாராயண விரதம் முன்பதிவு செய்யுங்கள்."),
            "te": T("సత్యనారాయణ వ్రతం", "పౌర్ణమి నాడు కథలోని ఐదు అధ్యాయాలతో పూర్తి వ్రతం", "పౌర్ణమి",
                    "సత్యనారాయణ వ్రతం పౌర్ణమి నాడు కథలోని ఐదు అధ్యాయాలు చదివి, ప్రసాదం నివేదించి చేస్తారు.",
                    [("సాంప్రదాయ ఉద్దేశం", "కుటుంబంలో శుభకార్యం తర్వాత కృతజ్ఞతగా చేస్తారు."),
                     ("పౌర్ణమి నాడు", "సంప్రదాయంగా పౌర్ణమి నాడు ఆచరిస్తారు."),
                     ("కథా పఠనం", "ఐదు అధ్యాయాలూ చదువుతారు.")],
                    [("సంకల్పం", "కుటుంబ పేర్లు మరియు గోత్రం చదువుతారు.", 0),
                     ("వ్రత పూజ", "తులసితో సత్యనారాయణ స్వామి పూజ.", 1),
                     ("కథ", "వ్రత కథలోని ఐదు అధ్యాయాలు.", 0),
                     ("హారతి మరియు ప్రసాదం", "హారతి మరియు ప్రసాద నివేదన.", 0)],
                    [("ఇది పూర్తి వ్రతమా?", "అవును. కథలోని ఐదు అధ్యాయాలూ చదువుతారు.")],
                    "పౌర్ణమి నాడు సత్యనారాయణ వ్రతం, హైదరాబాద్",
                    "మీ కుటుంబ పేర్లతో సంకల్పంతో సత్యనారాయణ వ్రతం బుక్ చేయండి."),
        },
    },
    {
        "key": "shani-chadhava", "temple": 1, "kind": "chadhava", "slug": "shani-chadhava",
        "deity_tags": ["shani"], "dosha_tags": ["shani"], "benefit_tags": ["harmony"],
        "tradition": "Smarta Vedic", "duration_minutes": 30, "priests_count": 1, "sankalp_language": "Sanskrit",
        "requires_nakshatra": False, "deliverables": ["sankalp_clip", "photos"], "prasad_box": None,
        "images": ["shani-chadhava"],
        "image_alt": alt("Oil vessel illustration", "तेल पात्र का चित्र", "எண்ணெய்ப் பாத்திரத்தின் ஓவியம்", "నూనె పాత్ర చిత్రం"),
        "prices": [(25100, 800), (35100, 1100), (45100, 1400)],
        "addons": [
            ("addon-oil", 15100, 500, 5, False, alt("Sesame oil abhishekam", "तिल के तेल का अभिषेक", "நல்லெண்ணெய் அபிஷேகம்", "నువ్వుల నూనె అభిషేకం")),
            ("addon-cloth", 25100, 800, 2, False, alt("Black cloth offering", "काले वस्त्र का अर्पण", "கருப்பு வஸ்திர சமர்ப்பணம்", "నల్ల వస్త్ర సమర్పణ")),
            ("addon-til", 5100, 200, 5, False, alt("Black sesame offering", "काले तिल का अर्पण", "கருப்பு எள் சமர்ப்பணம்", "నల్ల నువ్వుల సమర్పణ")),
            ("addon-diya", 5100, 200, 9, False, alt("Mustard oil lamp", "सरसों के तेल का दीपक", "கடுகு எண்ணெய் விளக்கு", "ఆవ నూనె దీపం")),
        ],
        "addon_names": {
            "addon-oil": {"en": "Sesame oil abhishekam", "hi": "तिल तेल अभिषेक", "ta": "நல்லெண்ணெய் அபிஷேகம்", "te": "నువ్వుల నూనె అభిషేకం"},
            "addon-cloth": {"en": "Black vastra", "hi": "काला वस्त्र", "ta": "கருப்பு வஸ்திரம்", "te": "నల్ల వస్త్రం"},
            "addon-til": {"en": "Black sesame (til)", "hi": "काले तिल", "ta": "கருப்பு எள்", "te": "నల్ల నువ్వులు"},
            "addon-diya": {"en": "Oil lamp", "hi": "तेल का दीपक", "ta": "எண்ணெய் விளக்கு", "te": "నూనె దీపం"},
        },
        "events": [(0, 19, 30), (7, 19, 30), (14, 19, 30)],
        "tr": {
            "en": T("Shani Chadhava", "Choose your offerings to Shani, placed at the shrine on Saturday", "Saturday",
                    "Choose the offerings you would like placed before Shani at the shrine. Each offering is named in the sankalp and appears in the video.",
                    [("Traditional purpose", "Saturday offerings to Shani are a long-standing tradition."),
                     ("You choose", "Pick the offerings and quantities you wish."),
                     ("Seen in the video", "Every offering is shown in your clip.")],
                    [("Sankalp", "Your name and the offerings are announced.", 0),
                     ("Chadhava", "Offerings are placed at the Shani shrine.", 1)],
                    [("Are the offerings sent to me?", "No. They are placed at the shrine and shown in the video.")],
                    "Shani Chadhava — Saturday offerings",
                    "Choose Shani offerings placed at the shrine on Saturday, with video on WhatsApp."),
            "hi": T("शनि चढ़ावा", "शनिवार को मंदिर में शनि को अपने चढ़ावे चुनें", "शनिवार",
                    "चुनें कि शनि के सामने कौन-से चढ़ावे रखे जाएँ। हर चढ़ावे का नाम संकल्प में लिया जाता है और वह वीडियो में दिखता है।",
                    [("पारंपरिक उद्देश्य", "शनिवार को शनि को चढ़ावा पुरानी परंपरा है।"),
                     ("आपकी पसंद", "चढ़ावे और उनकी मात्रा आप चुनें।"),
                     ("वीडियो में दिखता है", "हर चढ़ावा आपके क्लिप में दिखाया जाता है।")],
                    [("संकल्प", "आपका नाम और चढ़ावे बोले जाते हैं।", 0),
                     ("चढ़ावा", "चढ़ावे शनि सन्निधि में रखे जाते हैं।", 1)],
                    [("क्या चढ़ावे मुझे भेजे जाते हैं?", "नहीं। वे सन्निधि में रखे जाते हैं और वीडियो में दिखते हैं।")],
                    "शनि चढ़ावा — शनिवार के चढ़ावे",
                    "शनिवार को शनि सन्निधि में अपने चढ़ावे चुनें, WhatsApp पर वीडियो।"),
            "ta": T("சனி சமர்ப்பணம்", "சனிக்கிழமை சன்னதியில் வைக்க உங்கள் காணிக்கைகளைத் தேர்ந்தெடுங்கள்", "சனிக்கிழமை",
                    "சனி பகவான் முன் வைக்க விரும்பும் காணிக்கைகளைத் தேர்ந்தெடுங்கள். ஒவ்வொரு காணிக்கையும் சங்கல்பத்தில் சொல்லப்பட்டு காணொளியில் தெரியும்.",
                    [("பாரம்பரிய நோக்கம்", "சனிக்கிழமை சனி பகவானுக்குக் காணிக்கை நீண்ட பாரம்பரியம்."),
                     ("உங்கள் தேர்வு", "காணிக்கைகளையும் அளவையும் நீங்களே தேர்ந்தெடுக்கலாம்."),
                     ("காணொளியில் தெரியும்", "ஒவ்வொரு காணிக்கையும் உங்கள் கிளிப்பில் காட்டப்படும்.")],
                    [("சங்கல்பம்", "உங்கள் பெயரும் காணிக்கைகளும் சொல்லப்படும்.", 0),
                     ("சமர்ப்பணம்", "காணிக்கைகள் சனி சன்னதியில் வைக்கப்படும்.", 1)],
                    [("காணிக்கைகள் எனக்கு அனுப்பப்படுமா?", "இல்லை. அவை சன்னதியில் வைக்கப்பட்டு காணொளியில் காட்டப்படும்.")],
                    "சனி சமர்ப்பணம் — சனிக்கிழமை காணிக்கைகள்",
                    "சனிக்கிழமை சனி சன்னதியில் வைக்க காணிக்கைகளைத் தேர்ந்தெடுங்கள்."),
            "te": T("శని సమర్పణ", "శనివారం సన్నిధిలో ఉంచే మీ సమర్పణలు ఎంచుకోండి", "శనివారం",
                    "శని దేవుని ముందు ఉంచాలనుకునే సమర్పణలు ఎంచుకోండి. ప్రతి సమర్పణ సంకల్పంలో చెప్పబడి వీడియోలో కనిపిస్తుంది.",
                    [("సాంప్రదాయ ఉద్దేశం", "శనివారం శని దేవునికి సమర్పణ పాత సంప్రదాయం."),
                     ("మీ ఎంపిక", "సమర్పణలు మరియు పరిమాణం మీరే ఎంచుకోండి."),
                     ("వీడియోలో కనిపిస్తుంది", "ప్రతి సమర్పణ మీ క్లిప్‌లో చూపిస్తారు.")],
                    [("సంకల్పం", "మీ పేరు మరియు సమర్పణలు చెబుతారు.", 0),
                     ("సమర్పణ", "సమర్పణలు శని సన్నిధిలో ఉంచుతారు.", 1)],
                    [("సమర్పణలు నాకు పంపుతారా?", "లేదు. అవి సన్నిధిలో ఉంచి వీడియోలో చూపిస్తారు.")],
                    "శని సమర్పణ — శనివారం సమర్పణలు",
                    "శనివారం శని సన్నిధిలో ఉంచే సమర్పణలు ఎంచుకోండి, WhatsAppలో వీడియో."),
        },
    },
    {
        "key": "hanuman-seva", "temple": 0, "kind": "seva", "slug": "mangalavara-hanuman-seva",
        "deity_tags": ["hanuman"], "dosha_tags": [], "benefit_tags": ["courage"],
        "tradition": "Vaishnava", "duration_minutes": 45, "priests_count": 1, "sankalp_language": "Telugu",
        "requires_nakshatra": False, "deliverables": ["sankalp_clip", "photos"], "prasad_box": None,
        "images": ["hanuman-seva"],
        "image_alt": alt("Temple bell illustration", "मंदिर की घंटी का चित्र", "கோவில் மணியின் ஓவியம்", "ఆలయ గంట చిత్రం"),
        "prices": [(25100, 800), (35100, 1100), (45100, 1400)],
        "addons": [], "seva": {"rrule": "FREQ=WEEKLY;BYDAY=TU", "occurrences": 7, "first_weekday": 1, "hour": 7,
                               "minute": 30, "count": 12},
        "tr": {
            "en": T("Mangalavara Hanuman Seva — 7 Tuesdays", "Sindoor archana and Hanuman Chalisa every Tuesday for seven weeks", "7 Tuesdays",
                    "A recurring seva of sindoor archana and recitation of the Hanuman Chalisa on seven consecutive Tuesdays. Each Tuesday has its own sankalp and video.",
                    [("Traditional purpose", "Seven Tuesdays of Hanuman worship is a traditional vrata."),
                     ("Every Tuesday", "Each date gets its own sankalp and proof clip."),
                     ("Pay your way", "Pay in full, or by UPI AutoPay before each Tuesday.")],
                    [("Sankalp", "Your names are read each Tuesday.", 0),
                     ("Sindoor archana", "Archana with sindoor and tulsi.", 1),
                     ("Hanuman Chalisa", "Recitation of the Chalisa.", 0)],
                    [("Can I stop midway?", "Yes. Cancel remaining dates anytime from My Subscriptions.")],
                    "Mangalavara Hanuman Seva for 7 Tuesdays, Vijayawada",
                    "Book seven Tuesdays of Hanuman seva. Pay in full or by UPI AutoPay."),
            "hi": T("मंगलवार हनुमान सेवा — 7 मंगलवार", "सात सप्ताह तक हर मंगलवार सिंदूर अर्चना और हनुमान चालीसा", "7 मंगलवार",
                    "लगातार सात मंगलवार सिंदूर अर्चना और हनुमान चालीसा पाठ की सेवा। हर मंगलवार का अपना संकल्प और वीडियो होता है।",
                    [("पारंपरिक उद्देश्य", "सात मंगलवार हनुमान पूजा एक पारंपरिक व्रत है।"),
                     ("हर मंगलवार", "हर तारीख का अपना संकल्प और क्लिप।"),
                     ("भुगतान आपकी सुविधा से", "पूरा भुगतान, या हर मंगलवार से पहले UPI AutoPay।")],
                    [("संकल्प", "हर मंगलवार आपके नाम पढ़े जाते हैं।", 0),
                     ("सिंदूर अर्चना", "सिंदूर और तुलसी से अर्चना।", 1),
                     ("हनुमान चालीसा", "चालीसा का पाठ।", 0)],
                    [("क्या बीच में रोक सकते हैं?", "हाँ। My Subscriptions से कभी भी बची तारीखें रद्द करें।")],
                    "मंगलवार हनुमान सेवा, 7 मंगलवार, विजयवाड़ा",
                    "सात मंगलवार की हनुमान सेवा बुक करें। पूरा भुगतान या UPI AutoPay।"),
            "ta": T("செவ்வாய் அனுமன் சேவை — 7 செவ்வாய்கள்", "ஏழு வாரங்கள் ஒவ்வொரு செவ்வாயும் சிந்தூர அர்ச்சனை மற்றும் அனுமன் சாலீசா", "7 செவ்வாய்கள்",
                    "தொடர்ந்து ஏழு செவ்வாய்க்கிழமைகள் சிந்தூர அர்ச்சனை மற்றும் அனுமன் சாலீசா பாராயண சேவை. ஒவ்வொரு செவ்வாய்க்கும் தனி சங்கல்பமும் காணொளியும்.",
                    [("பாரம்பரிய நோக்கம்", "ஏழு செவ்வாய் அனுமன் வழிபாடு ஒரு பாரம்பரிய விரதம்."),
                     ("ஒவ்வொரு செவ்வாயும்", "ஒவ்வொரு தேதிக்கும் தனி சங்கல்பமும் கிளிப்பும்."),
                     ("உங்கள் வசதிப்படி", "முழுமையாகச் செலுத்தலாம் அல்லது UPI AutoPay.")],
                    [("சங்கல்பம்", "ஒவ்வொரு செவ்வாயும் உங்கள் பெயர்கள் வாசிக்கப்படும்.", 0),
                     ("சிந்தூர அர்ச்சனை", "சிந்தூரம், துளசியுடன் அர்ச்சனை.", 1),
                     ("அனுமன் சாலீசா", "சாலீசா பாராயணம்.", 0)],
                    [("இடையில் நிறுத்தலாமா?", "ஆம். My Subscriptions இல் மீதமுள்ள தேதிகளை எப்போது வேண்டுமானாலும் ரத்து செய்யலாம்.")],
                    "செவ்வாய் அனுமன் சேவை, 7 செவ்வாய்கள், விஜயவாடா",
                    "ஏழு செவ்வாய் அனுமன் சேவையை முன்பதிவு செய்யுங்கள். முழுக் கட்டணம் அல்லது UPI AutoPay."),
            "te": T("మంగళవార హనుమాన్ సేవ — 7 మంగళవారాలు", "ఏడు వారాల పాటు ప్రతి మంగళవారం సిందూర అర్చన మరియు హనుమాన్ చాలీసా", "7 మంగళవారాలు",
                    "వరుసగా ఏడు మంగళవారాలు సిందూర అర్చన మరియు హనుమాన్ చాలీసా పఠన సేవ. ప్రతి మంగళవారానికి ప్రత్యేక సంకల్పం మరియు వీడియో.",
                    [("సాంప్రదాయ ఉద్దేశం", "ఏడు మంగళవారాల హనుమాన్ పూజ సాంప్రదాయ వ్రతం."),
                     ("ప్రతి మంగళవారం", "ప్రతి తేదీకి ప్రత్యేక సంకల్పం మరియు క్లిప్."),
                     ("మీకు అనుకూలంగా", "పూర్తిగా చెల్లించండి లేదా UPI AutoPay.")],
                    [("సంకల్పం", "ప్రతి మంగళవారం మీ పేర్లు చదువుతారు.", 0),
                     ("సిందూర అర్చన", "సిందూరం, తులసితో అర్చన.", 1),
                     ("హనుమాన్ చాలీసా", "చాలీసా పఠనం.", 0)],
                    [("మధ్యలో ఆపవచ్చా?", "అవును. My Subscriptions నుండి మిగిలిన తేదీలు ఎప్పుడైనా రద్దు చేయండి.")],
                    "మంగళవార హనుమాన్ సేవ, 7 మంగళవారాలు, విజయవాడ",
                    "ఏడు మంగళవారాల హనుమాన్ సేవ బుక్ చేయండి. పూర్తి చెల్లింపు లేదా UPI AutoPay."),
        },
    },
    {
        "key": "deepa-seva", "temple": 3, "kind": "seva", "slug": "nitya-deepa-seva",
        "deity_tags": ["lakshmi"], "dosha_tags": [], "benefit_tags": ["gratitude"],
        "tradition": "Pancharatra", "duration_minutes": 15, "priests_count": 1, "sankalp_language": "Telugu",
        "requires_nakshatra": False, "deliverables": ["sankalp_clip"], "prasad_box": None, "images": ["deepa-seva"],
        "image_alt": alt("Ghee lamp illustration", "घी के दीपक का चित्र", "நெய் விளக்கின் ஓவியம்", "నెయ్యి దీపం చిత్రం"),
        "prices": [(10100, 300), (15100, 500), (20100, 700)],
        "addons": [], "seva": {"rrule": "FREQ=DAILY", "occurrences": 3, "first_weekday": None, "hour": 18, "minute": 0,
                               "count": 14},
        "tr": {
            "en": T("Nitya Deepa Seva — 3 evenings", "A ghee lamp lit in your name before Mahalakshmi on three evenings", "Daily",
                    "A ghee lamp is lit before Mahalakshmi at the evening aarti, in your name, on three consecutive evenings.",
                    [("Traditional purpose", "Lighting a lamp is the simplest daily offering."),
                     ("Three evenings", "One lamp each evening, each with its own clip."),
                     ("Short and simple", "A brief sankalp at the evening aarti.")],
                    [("Sankalp", "Your name is read at the evening aarti.", 0),
                     ("Deepa", "The ghee lamp is lit before the deity.", 1)],
                    [("When is the lamp lit?", "At the evening aarti, at the time shown for each date.")],
                    "Nitya Deepa Seva at Sri Mahalakshmi Temple",
                    "A ghee lamp lit in your name on three evenings, with a clip each day."),
            "hi": T("नित्य दीप सेवा — 3 शामें", "तीन शामों तक आपके नाम से महालक्ष्मी के सामने घी का दीपक", "दैनिक",
                    "लगातार तीन शाम आरती के समय आपके नाम से महालक्ष्मी के सामने घी का दीपक जलाया जाता है।",
                    [("पारंपरिक उद्देश्य", "दीपक जलाना सबसे सरल दैनिक अर्पण है।"),
                     ("तीन शामें", "हर शाम एक दीपक, हर दिन का अपना क्लिप।"),
                     ("सरल और छोटा", "शाम की आरती में संक्षिप्त संकल्प।")],
                    [("संकल्प", "शाम की आरती में आपका नाम पढ़ा जाता है।", 0),
                     ("दीप", "देवी के सामने घी का दीपक जलाया जाता है।", 1)],
                    [("दीपक कब जलता है?", "हर तारीख के लिए दिखाए गए समय पर, शाम की आरती में।")],
                    "नित्य दीप सेवा, श्री महालक्ष्मी मंदिर",
                    "तीन शामों तक आपके नाम से घी का दीपक, हर दिन क्लिप के साथ।"),
            "ta": T("நித்ய தீப சேவை — 3 மாலைகள்", "மூன்று மாலைகள் உங்கள் பெயரில் மகாலட்சுமி முன் நெய் விளக்கு", "தினசரி",
                    "தொடர்ந்து மூன்று மாலைகள் ஆரத்தியின்போது உங்கள் பெயரில் மகாலட்சுமி முன் நெய் விளக்கு ஏற்றப்படுகிறது.",
                    [("பாரம்பரிய நோக்கம்", "விளக்கேற்றுதல் மிக எளிய தினசரி காணிக்கை."),
                     ("மூன்று மாலைகள்", "ஒவ்வொரு மாலையும் ஒரு விளக்கு, தனி கிளிப்."),
                     ("எளிமையானது", "மாலை ஆரத்தியில் சுருக்கமான சங்கல்பம்.")],
                    [("சங்கல்பம்", "மாலை ஆரத்தியில் உங்கள் பெயர் வாசிக்கப்படும்.", 0),
                     ("தீபம்", "தெய்வத்தின் முன் நெய் விளக்கு ஏற்றப்படும்.", 1)],
                    [("விளக்கு எப்போது ஏற்றப்படும்?", "ஒவ்வொரு தேதிக்கும் காட்டப்படும் நேரத்தில், மாலை ஆரத்தியில்.")],
                    "நித்ய தீப சேவை, ஸ்ரீ மகாலட்சுமி கோவில்",
                    "மூன்று மாலைகள் உங்கள் பெயரில் நெய் விளக்கு, ஒவ்வொரு நாளும் கிளிப்."),
            "te": T("నిత్య దీప సేవ — 3 సాయంత్రాలు", "మూడు సాయంత్రాలు మీ పేరుతో మహాలక్ష్మి ముందు నెయ్యి దీపం", "రోజువారీ",
                    "వరుసగా మూడు సాయంత్రాలు హారతి సమయంలో మీ పేరుతో మహాలక్ష్మి ముందు నెయ్యి దీపం వెలిగిస్తారు.",
                    [("సాంప్రదాయ ఉద్దేశం", "దీపం వెలిగించడం అత్యంత సరళమైన రోజువారీ సమర్పణ."),
                     ("మూడు సాయంత్రాలు", "ప్రతి సాయంత్రం ఒక దీపం, ప్రత్యేక క్లిప్."),
                     ("సరళంగా", "సాయంత్రం హారతిలో చిన్న సంకల్పం.")],
                    [("సంకల్పం", "సాయంత్రం హారతిలో మీ పేరు చదువుతారు.", 0),
                     ("దీపం", "దేవి ముందు నెయ్యి దీపం వెలిగిస్తారు.", 1)],
                    [("దీపం ఎప్పుడు వెలిగిస్తారు?", "ప్రతి తేదీకి చూపిన సమయంలో, సాయంత్రం హారతిలో.")],
                    "నిత్య దీప సేవ, శ్రీ మహాలక్ష్మి ఆలయం",
                    "మూడు సాయంత్రాలు మీ పేరుతో నెయ్యి దీపం, ప్రతిరోజూ క్లిప్."),
        },
    },
]

ADDON_NAMES = {
    "addon-flowers": {"en": "Flowers for archana", "hi": "अर्चना के लिए फूल", "ta": "அர்ச்சனைப் பூக்கள்", "te": "అర్చన పూలు"},
    "addon-diya": {"en": "Ghee lamp", "hi": "घी का दीपक", "ta": "நெய் விளக்கு", "te": "నెయ్యి దీపం"},
    "addon-coconut": {"en": "Blessed coconut, sent home", "hi": "अभिमंत्रित नारियल, घर भेजा जाएगा",
                      "ta": "வீட்டுக்கு அனுப்பப்படும் தேங்காய்", "te": "ఇంటికి పంపే నారికేళం"},
}

# Global FAQs (8 per locale). Tokens in {braces} render from site_config at display time, so no promise is
# ever typed twice (PRD §12).
FAQS = {
    "en": [
        ("Do I need to be present at the puja?", "No. The priests take the sankalp in the names and gotra you give us, and you receive the video on WhatsApp."),
        ("When will I receive the video?", "Within {video_sla_hours} hours of the puja, unless a different time is shown on the puja page."),
        ("What if I don't know my gotra?", "Tick \"I don't know my gotra\". The priest will use {gotra_fallback} gotra, as is traditional."),
        ("Can I cancel?", "Yes, for free until the booking cutoff, {booking_cutoff_hours} hours before the puja. After that the sankalp sheet is printed and cancellation is not possible."),
        ("How do refunds work?", "Refunds go back to your original payment method and usually arrive in {refund_days} working days."),
        ("Can I book for my parents?", "Yes. Choose the Couple or Family package and add their names. The video can be forwarded to them."),
        ("I live outside India. Can I book?", "Yes. You can pay in USD by international card, and we show the puja time in IST and your local time."),
        ("How do I reach support?", "Message us on WhatsApp or call during {support_hours}."),
    ],
    "hi": [
        ("क्या मुझे पूजा में उपस्थित रहना होगा?", "नहीं। पुजारी आपके दिए नाम और गोत्र से संकल्प लेते हैं, और वीडियो WhatsApp पर मिलता है।"),
        ("वीडियो कब मिलेगा?", "पूजा के {video_sla_hours} घंटे के भीतर, जब तक पूजा पेज पर अलग समय न दिखाया गया हो।"),
        ("अगर मुझे अपना गोत्र नहीं पता?", "\"मुझे अपना गोत्र नहीं पता\" चुनें। परंपरा के अनुसार पुजारी {gotra_fallback} गोत्र लेंगे।"),
        ("क्या मैं रद्द कर सकता हूँ?", "हाँ, बुकिंग कटऑफ तक मुफ़्त, यानी पूजा से {booking_cutoff_hours} घंटे पहले तक। उसके बाद संकल्प सूची छप जाती है और रद्द नहीं होता।"),
        ("रिफ़ंड कैसे होता है?", "रिफ़ंड आपके मूल भुगतान माध्यम पर जाता है और आमतौर पर {refund_days} कार्यदिवसों में पहुँचता है।"),
        ("क्या मैं माता-पिता के लिए बुक कर सकता हूँ?", "हाँ। दंपति या परिवार पैकेज चुनें और उनके नाम जोड़ें। वीडियो उन्हें फ़ॉरवर्ड किया जा सकता है।"),
        ("मैं भारत से बाहर रहता हूँ। क्या बुक कर सकता हूँ?", "हाँ। अंतरराष्ट्रीय कार्ड से USD में भुगतान करें; पूजा का समय IST और आपके स्थानीय समय में दिखता है।"),
        ("सहायता से कैसे संपर्क करें?", "WhatsApp पर संदेश भेजें या {support_hours} के दौरान कॉल करें।"),
    ],
    "ta": [
        ("பூஜையில் நான் நேரில் இருக்க வேண்டுமா?", "இல்லை. நீங்கள் கொடுக்கும் பெயர், கோத்திரத்தில் அர்ச்சகர்கள் சங்கல்பம் செய்வார்கள்; காணொளி WhatsApp இல் வரும்."),
        ("காணொளி எப்போது வரும்?", "பூஜை முடிந்து {video_sla_hours} மணி நேரத்திற்குள், பூஜைப் பக்கத்தில் வேறு நேரம் காட்டப்படாவிட்டால்."),
        ("என் கோத்திரம் தெரியாவிட்டால்?", "\"என் கோத்திரம் தெரியாது\" என்பதைத் தேர்ந்தெடுக்கவும். பாரம்பரியப்படி அர்ச்சகர் {gotra_fallback} கோத்திரத்தைப் பயன்படுத்துவார்."),
        ("ரத்து செய்யலாமா?", "ஆம், பூஜைக்கு {booking_cutoff_hours} மணி நேரம் முன்பு வரை இலவசமாக. அதன் பிறகு சங்கல்பப் பட்டியல் அச்சிடப்படுவதால் ரத்து செய்ய இயலாது."),
        ("பணம் எப்படித் திரும்பக் கிடைக்கும்?", "உங்கள் அசல் கட்டண முறைக்கே திருப்பப்படும்; வழக்கமாக {refund_days} வேலை நாட்களில் வரும்."),
        ("பெற்றோருக்காக முன்பதிவு செய்யலாமா?", "ஆம். தம்பதி அல்லது குடும்பத் தொகுப்பைத் தேர்ந்தெடுத்து அவர்கள் பெயர்களைச் சேர்க்கவும்."),
        ("நான் இந்தியாவுக்கு வெளியே இருக்கிறேன். முன்பதிவு செய்யலாமா?", "ஆம். சர்வதேச அட்டை மூலம் USD இல் செலுத்தலாம்; பூஜை நேரம் IST மற்றும் உங்கள் உள்ளூர் நேரத்தில் காட்டப்படும்."),
        ("உதவிக்கு எப்படித் தொடர்புகொள்வது?", "WhatsApp இல் செய்தி அனுப்புங்கள் அல்லது {support_hours} நேரத்தில் அழையுங்கள்."),
    ],
    "te": [
        ("పూజకు నేను హాజరు కావాలా?", "అవసరం లేదు. మీరు ఇచ్చిన పేర్లు మరియు గోత్రంతో అర్చకులు సంకల్పం చేస్తారు; వీడియో WhatsAppలో వస్తుంది."),
        ("వీడియో ఎప్పుడు వస్తుంది?", "పూజ జరిగిన {video_sla_hours} గంటల్లోపు, పూజ పేజీలో వేరే సమయం చూపకపోతే."),
        ("నా గోత్రం తెలియకపోతే?", "\"నా గోత్రం తెలియదు\" ఎంచుకోండి. సంప్రదాయం ప్రకారం అర్చకులు {gotra_fallback} గోత్రం వాడతారు."),
        ("రద్దు చేయవచ్చా?", "అవును, పూజకు {booking_cutoff_hours} గంటల ముందు వరకు ఉచితంగా. ఆ తర్వాత సంకల్ప పత్రం ముద్రించబడుతుంది కాబట్టి రద్దు కుదరదు."),
        ("రీఫండ్ ఎలా వస్తుంది?", "రీఫండ్ మీ అసలు చెల్లింపు పద్ధతికే వెళ్తుంది; సాధారణంగా {refund_days} పని దినాల్లో అందుతుంది."),
        ("తల్లిదండ్రుల కోసం బుక్ చేయవచ్చా?", "అవును. దంపతులు లేదా కుటుంబ ప్యాకేజీ ఎంచుకుని వారి పేర్లు చేర్చండి. వీడియోను వారికి ఫార్వర్డ్ చేయవచ్చు."),
        ("నేను భారతదేశం బయట ఉంటాను. బుక్ చేయవచ్చా?", "అవును. అంతర్జాతీయ కార్డుతో USDలో చెల్లించవచ్చు; పూజ సమయం IST మరియు మీ స్థానిక సమయంలో చూపిస్తాము."),
        ("సహాయం కోసం ఎలా సంప్రదించాలి?", "WhatsAppలో సందేశం పంపండి లేదా {support_hours} సమయంలో కాల్ చేయండి."),
    ],
}
